apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-pw
  namespace: pingpong
spec:
  encryptedData:
    # passw0rd
    POSTGRES_PASSWORD: AgCiQJvFJWBiAy34MkWugi7bdoz0zbig6nSOHgv1XxsfXSf37Hvtm0jXCs1JfMnRt3wlQFuUbtWsioNCeqiU3VnrJVc70nEXEJniNqLMZeRb+G9MvXqT8uWlnqE+mCLQsWEPqWV+GkYsAnfyKbtClgWyNF82V5YH1Vdy3JRsPzvE5o1ookUDo8SjkBHHDP3AwF8oAMO55H2um9K3AD5Mrfu+IU+Scq0uSvLH9XJehfsgc6vjBAkmEO/RzFwrsBQ/hTCERqo2pZRdME9f+khBuFLe45k7bV8fUoqF4eJzPtj87SWpxrhUnqNxiinxXnC/HZfBOWZrGDqqPW1xhcEttO1hTIg+uv4scH/pAWmD8eWZxCglFcJO8dFGK5WZlV18xdrMiDEz5wQDNkp/JBS5vxw2ZfedrBY6kZkYfl74Q+fPauA5io2kadsmAxQ2Jr/Nvp8MepYeUejiBEqJrUxOgvuVZKQUlIAsgYzlAEuiIZwUPEUVdNDPpPlrZIyMsV2b/8pJuB2+pRlDucPm4sPym7uDrIqOrQq1GqoLieRXKcGcj+upc41wVjBLR8ICYS5uUe41I1MGryeXSw4KY0EyHQRq3DhBpTbJ+bi/1z7T7ZR11MUI7b8VJp2PC2ts2qSYAZS1L5aCyUinCD+SnKPNuukHGbFgP9UM5tNS5sApXGm3D90t9o6FrwRjRWDjYzBlGb8vI+ltTv6H/A4=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-pw
      namespace: pingpong
