apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: project-ingress
  namespace: project
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      # prevent /api/healthz from being publicly accessible
      match: (PathPrefix(`/api/todos`)||PathPrefix(`/api/static`))
      services:
        - name: project-svc
          port: 3030
    - kind: Rule
      match: PathPrefix(`/`)
      services:
        - name: project-svc
          port: 8080
    - kind: Rule
      match: PathPrefix(`/static`)
      services:
        - name: project-svc
          port: 8080
