apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
  namespace: hashgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      containers:
        - name: hashgenerator-server
          image: movd/devopswithkubernetes-hashgenerator-server:sha-3479d69
          env:
            - name: SERVER_PORT
              value: "3001"
            - name: HASHGENERATOR_URL
              # 2345 is mapped to port 3002 of generator
              value: "http://hashgenerator-svc:2345/"
            - name: PINGPONG_URL
              # ping pong lives in another namespace
              value: "http://pingpong-svc.pingpong:6789/pingpong"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
        - name: hashgenerator
          image: movd/devopswithkubernetes-hashgenerator:sha-3479d69
          env:
            - name: GENERATOR_PORT
              value: "3002"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
