apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator
spec:
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      containers:
        - name: hashgenerator
          image: movd/devopswithkubernetes-hashgenerator:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
