apiVersion: v1
kind: Service
metadata:
  name: hashgenerator-svc-loadbalancer
  namespace: hashgenerator
spec:
  type: LoadBalancer
  selector:
    app: hashgenerator
  ports:
    - name: server
      port: 80
      protocol: TCP
      targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: hashgenerator-svc
  namespace: hashgenerator
spec:
  type: ClusterIP
  selector:
    app: hashgenerator
  ports:
    - name: generator
      port: 2345
      protocol: TCP
      targetPort: 3002
