apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc-loadbalancer
  namespace: pingpong
spec:
  type: LoadBalancer
  selector:
    app: pingpong
  ports:
    - name: express
      port: 80
      protocol: TCP
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: pingpong
spec:
  type: ClusterIP
  selector:
    app: pingpong
  ports:
    - name: express
      port: 6789
      protocol: TCP
      targetPort: 3000
