name: "build project-frontend:dev"

on:
  push:
    paths:
      - "project/frontend/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2
      - name: Build and push docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          repository: movd/devopswithkubernetes-project-frontend
          path: ./project/frontend
          tags: dev
          tag_with_sha: true
