name: "build movd/devopswithkubernetes-project:dev"

on:
  push:
    branches: [master]
    paths:
      - "project/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2
      - name: Build and push docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          repository: movd/devopswithkubernetes-project
          path: ./project
          tags: dev
          tag_with_sha: true
