name: "build project-backend:latest"

on:
  push:
    tags:
      - v*
    paths:
      - "project/backend/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2
      - name: Build and push docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          repository: movd/devopswithkubernetes-project-backend
          path: ./project/backend
          tags: latest
          tag_with_ref: true
          tag_with_sha: true
